# The URL the site will be built for
# base_url = "192.168.29.180:1111"
base_url = "https://arky.pages.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here

[extra.favourites]
"🎨 Artists"  = ["Jeremy Zucker", "Tove Lo", "Sabrina Carpenter", "Ariana Grande", "Paramore", "Jojo", "Far East Movement"]
"📚 Books"    = ["Apocalypse Triptych Series", "Dreamers", "Age of Miracles", "Lucifer's Hammer", "Animal Farm", "The Rapture"]
"🌈 Colours"  = ["Pastels", "Sepia", "Peach Fuzz", "Salmon"]
"🔤 Fonts"    = ["Jost", "Jetbrains Mono", "Roboto Flex"]
"🎮 Games"    = ["Dota", "Minecraft", "Age of Mythology", "Pokemon (+ rom hacks)", "No Man's Sky", "The Forest"]
"👾 Pokemon"  = ["Meganium", "Cooperajah", "Zangoose", "Mewtwo", "Vileplume", "Dodrio"]
"🎬 Movies"   = ["Interstellar", "The Grinch", "Cat in the hat", "War of the worlds", "Melancholia", "Cloverfield", "2012"]
"📺 TV Shows" = ["How I Met Your Mother", "Altered Carbon", "Chernobyl", "Wandavision", "The Originals", "Loki", "Stranger Things"]